Init project
netless-io/netless-combine-player pull request #6
Opened 2020-10-14 08:40 UTC by BlackHole1

2020-10-14 10:47 UTC, Moskize91 requested changes
1. ``BaseStatusData`` 类型的 ``currentIndex`` 和 ``lastIndex`` 应该直接使用枚举类型，而不是用 index 转来转去。``enum`` 可以直接定义成数字，也可以起到索引效果。

2. 重新设计 getCombinationStatus() 返回的内容。

``CombinationStatus`` 应该包含两个索引 ``index`` 对应的枚举值。因此，应该重构 ``initTables`` 构造的列表，让其包含正确的 CombinationStatus 值。

3. 不要写类似 ``source: "video" | "whiteboard"`` 的类型，直接写成枚举类型即可。

2020-10-15 05:17 UTC, Moskize91 requested changes

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +const baseStatus = [
删掉吧，不用 index 的形式这个就没用了

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +const baseStatusData: BaseStatusData = {
这个删掉吧，没用了

2020-10-15 05:17 UTC, Moskize91 commented on src/Types.ts
> +    status: readonly Status[];
这个字段没用了，删掉就行了

2020-10-15 05:17 UTC, Moskize91 commented on src/Types.ts
> +    current: Status | "";
不要用 ``Status | ""`` 修饰类型，直接 ``Status`` 就行了。一开始就在参数里要求初始化，不要认为制造类似 ``null`` 的可能性。

2020-10-15 05:17 UTC, Moskize91 commented on src/Types.ts
> +    last: Status | "";
同上，重命名成 ``previous``

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    private videoStatus: BaseStatusData = {
应为 readonly

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    private whiteboardStatus: BaseStatusData = {
应为 readonly

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +        status: false,
重名名为 ``isLocked``

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    private lockInfo: LockStatus = {
重命名为 ``statusLockInfo。
类型也不要叫 LockStatus，叫 LockInfo 吧

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    private readonly table: { name: CombineStatus; event: EmptyCallback }[][];
类型应为 ``{ readonly name: CombineStatus; readonly  event: EmptyCallback }``

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    public one(eventName: CombineStatus, cb: OnEventCallback): void {
不要用回调，用 promise。改成：
```typescript
one(eventName: CombineStatus): Promise<void>;
```

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    public emit(source: Source, status: Status): void {
emit 不是这个意思，这里重命名为 setStatus

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    public lockStatus(allowStatusList: CombineStatus[], unLockStatusList: CombineStatus[]): void {
重命名为 lockCombineStatus

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +        last: CombineStatus | undefined;
- 返回值类型定义 type，再写 type 名，不要直接写，太难看了。
- 返回值不要 ``| undefined``。status 一开始就是确定的，无需 ``undefined``

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    public getStatus(
同上一个方法，不要这么多回车，返回值写 type 名字

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +        if (source === Source.Video) {
用 switch case 对应枚举

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    private setLastIndex(whiteboard: Status, video: Status): void {
命名有问题，没有 Index 了

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    private generateEvent(status: CombineStatus) {
- 返回值类型用 type 命名代替
- 简短参数列表没必要用回车间隔

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +                const last = {
定义 object 的时候必须加上类型

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +                const current = {
定义 object 的时候必须加上类型

2020-10-15 05:17 UTC, Moskize91 commented on src/StateMachine.ts
> +    private initTables(): { name: CombineStatus; event: EmptyCallback }[][] {
应该返回不可修改的二维数组

2020-10-15 07:53 UTC, Moskize91 requested changes

2020-10-15 07:53 UTC, Moskize91 commented on src/StateMachine.ts
> +        switch (source) {
switch case 要用 {...} 把代码包起来

2020-10-15 07:53 UTC, Moskize91 commented on src/StateMachine.ts
> +        switch (source) {
switch case 要用 {...} 把代码包起来

2020-10-15 07:53 UTC, Moskize91 commented on src/StateMachine.ts
> +    public unLockStatus(): void {
unLockStatus 应该为 unlockCombineStatus，与 lockCombineStatus 是对应关系

2020-10-15 07:53 UTC, Moskize91 commented on src/StateMachine.ts
> +    private generateEvent(status: CombineStatus): GenerateEvent {
``generateEvent`` 和 ``initTables`` 的用法比较诡异，难以理解。但其实可以把它改得比较简洁和直接的。

你可以让 ``initTables()`` 返回一个二维数组，元素是一个 object 同时包含：``combineStatus``、``whiteboardStatus``、``videoStatus``。

然后将将 ``event()`` 方法写成传入该 object 的一个 ``private method`` 即可。

2020-10-15 07:53 UTC, Moskize91 commented on src/StateMachine.ts
> +        return Object.freeze(result);
这个只能将最外层 array 冻结，不能将次级结构冻结

2020-10-15 10:08 UTC, Moskize91 requested changes

2020-10-15 10:08 UTC, Moskize91 commented on src/StatusContant.ts
> +export enum Status {
不要叫 status，信息量太低。叫 ``AtomPlayerStatus`` 吧，和文档对应。

2020-10-15 10:08 UTC, Moskize91 commented on src/StatusContant.ts
> +export enum CombineStatus {
改成 ``CombinePlayerStatus`` 与 ``AtomPlayerStatus`` 对应

2020-10-15 10:08 UTC, Moskize91 commented on src/StatusContant.ts
> +export enum Source {
改成 ``AtomPlayerSource``

2020-10-15 10:08 UTC, Moskize91 commented on src/StatusContant.ts
> +    Video = "Video",
这个类型没对外暴露，都可以改成 number 类型，而非 string

2020-10-15 10:08 UTC, Moskize91 commented on src/StatusContant.ts
> +    None = "None",
这个类型没对外暴露，都可以改成 number 类型，而非 string

2020-10-15 10:08 UTC, Moskize91 commented on src/Types.ts
> +export interface VideoOptions extends DefaultOptions {
所有的字段前加上`` readonly``

2020-10-15 10:08 UTC, Moskize91 commented on src/Types.ts
> +export interface DefaultOptions {
- 什么的 default？没有表明，应该叫 VideoDefaultOptions。
- 所有的字段前加上`` readonly``

2020-10-15 10:08 UTC, Moskize91 commented on src/Types.ts
> +    videoJsOptions?: VideoJsPlayerOptions;
``DefaultOptions`` 里已经有这个字段了，可以删掉

2020-10-15 10:08 UTC, Moskize91 commented on src/Types.ts
> +export type Mixing = {
不要命名这种 Mixing 没有定语指向太范的名字。

叫 ``AtomPlayerStatusPair`` 吧

2020-10-15 10:08 UTC, Moskize91 commented on src/Types.ts
> +    allowStatusList: CombineStatus[];
类型应该为 ``readonly CombineStatus[]``，下一行一样

2020-10-15 10:08 UTC, Moskize91 commented on src/Types.ts
> +export type StatusData = {
- 改成 ``AtomPlayerStatusTransfer``
- 字段都要 ``readonly``

2020-10-15 10:08 UTC, Moskize91 commented on src/Types.ts
> +export type Table = readonly (readonly TableData[])[];
这是 ``StateMachine.ts`` 的私有类型吧，迁移过去，不应该出现在这。

2020-10-15 10:08 UTC, Moskize91 commented on src/Types.ts
> +export type CombinationStatusData = {
- 改成 ``CombinePlayerStatusTransfer``
- 统一用词，一会 Combination 一会 combine 很奇怪
- 字段应该加上 readonly

2020-10-15 10:08 UTC, Moskize91 commented on src/Types.ts
> +export type TableData = {
这个也应该是 ``StateMachine.ts`` 的私有类型

2020-10-15 10:14 UTC, Moskize91 requested changes

2020-10-15 10:14 UTC, Moskize91 commented on src/StateMachine.ts
> +        const generateTable = (combineStatus: CombineStatus): GenerateTable => {
- 这个方法可以写成成员方法，而不是闭包。暂时没看出必须写成闭包的理由。
- 这个方法改成下面这个样子是等效的吧。

```typescript
const generateTable = (combineStatus: CombineStatus, whiteboardStatus: Status, videoStatus: Status): TableData => {
            return Object.freeze({
                combineStatus,
                whiteboardStatus,
                videoStatus,
            });
        };
```

2020-10-15 10:14 UTC, Moskize91 commented on src/StateMachine.ts
> +    private eventHandler(tableData: TableData): void {
方法必须是名词：handleEvent 如何？

2020-10-15 10:21 UTC, BlackHole1 commented on src/StateMachine.ts
> +        const generateTable = (combineStatus: CombineStatus): GenerateTable => {
这样可以的，只是代码会比较丑，不直观。如:

```typescript
[
    generateTable(CombineStatus.PauseSeeking, Status.PauseSeeking, Status.PauseSeeking),
    generateTable(CombineStatus.PauseSeeking, Status.PauseSeeking, Status.Pause),
    generateTable(CombineStatus.Disabled, Status.PauseSeeking, Status.PauseBuffering),
    generateTable(CombineStatus.Disabled, Status.PauseSeeking, Status.PlayingBuffering),
    ...
]
```
而使用目前的柯里化写法的话，代码比较直观:
```
[
     pauseSeeking(Status.PauseSeeking, Status.PauseSeeking),
     pauseSeeking(Status.PauseSeeking, Status.Pause),
     disabled(Status.PauseSeeking, Status.PauseBuffering),
     disabled(Status.PauseSeeking, Status.PlayingBuffering),
     ...
]
```

2020-10-15 10:22 UTC, BlackHole1 commented on src/StateMachine.ts
> +    private eventHandler(tableData: TableData): void {
可以的，学习了。

2020-10-16 03:22 UTC, Moskize91 commented on src/StateMachine.ts
> +        const generateTable = (combineStatus: CombineStatus): GenerateTable => {
行吧，你注释一下，是为了美观。

2020-10-16 03:42 UTC, Moskize91 requested changes

2020-10-16 03:42 UTC, Moskize91 commented on src/index.ts
> +    private videoJS: VideoJsPlayer | undefined = undefined;
videoJS 和 whiteboard 都应该是 readonly，并在 constructor 中构造好。

videoJS 改名 ``video`` 就行了。

2020-10-16 03:42 UTC, Moskize91 commented on src/index.ts
> +    public constructor(videoOptions: VideoOptions, debug: boolean = false) {
建议用 factory 模式构造该对象，然后将构造好的 video、whiteboard 直接传入 ``CombinePlayer`` 的构造参数。这样可以确保这两个属性是 ``private readonly`` 的形式，再将所有判断它们 ``null`` 的逻辑删除。

构造这 video、whiteboard 比较复杂，可以另外新建一个 CombinePlayerFactory 的文件来写这部分逻辑。

2020-10-16 06:06 UTC, Moskize91 requested changes

2020-10-16 06:06 UTC, Moskize91 commented on src/CombinePlayerFactory.ts
> +const videoDefaultOptions = (): VideoDefaultOptions => {
这个写成 CombinePlayerFactory 的成员方法吧，static 也行

2020-10-16 06:06 UTC, Moskize91 commented on src/CombinePlayerFactory.ts
> +    private whiteboard: Player | undefined = undefined;
可写成 ``private whiteboard?: Player = undefined;``

2020-10-16 06:06 UTC, Moskize91 commented on src/CombinePlayerFactory.ts
> +    public setWhiteboardEvents(phase: PlayerPhase): void {
不用外界主动调用。直接：https://developer.netless.link/javascript-zh/home/construct-room-and-player#onisplayablechanged

2020-10-16 06:06 UTC, Moskize91 commented on src/CombinePlayerFactory.ts
> +    public setWhiteboardIsPlayable(isPlayable: boolean): void {
不用外界主动调用：直接注册：https://developer.netless.link/javascript-zh/home/construct-room-and-player#onisplayablechanged

2020-10-16 06:06 UTC, Moskize91 commented on src/CombinePlayerFactory.ts
> +export class CombinePlayerFactory {
一般工厂模式，用户会调用工厂的类似 ``create`` 的方法来创建 CombinePlayer 对象。
你需要做如下调整。

1. 将 ``class CombinePlayer`` 改成 ``interface CombinePlayer``
2. 将原来的 ``CombinePlayer`` 改成 ``CombinePlayerImplement`` 并实现 ``interface CombinePlayer``
3. 在 factory 里加一个 ``create`` 方法，返回类型为 ``CombinePlayer``，但实际上返回 ``CombinePlayerImplement`` 对象。做到将 ``CombinePlayerImplement`` 封装到内部不对外暴露。

2020-10-16 07:42 UTC, BlackHole1 commented on src/StateMachine.ts
> +        this.events[eventName] = {
看上去应该可以使用: `EventEmmit` 来代替

2020-10-16 10:03 UTC, Moskize91 requested changes

2020-10-16 10:03 UTC, Moskize91 commented on src/index.ts
> +export default class CombinePlayerImplement implements CombinePlayer {
建议全部把这个 class 挪到 ``CombinePlayerImplement.ts`` 文件中。因为用户能取到的类型都在 ``index.ts`` 里，而 CombinePlayerImplement 我们作为内部类，只有``CombinePlayer`` 是暴露的。

2020-10-16 10:03 UTC, Moskize91 commented on src/index.ts
> +    private statusCallBack: (status: PublicCombinedStatus, message?: string) => any = () => {};
改成 ``private onStatusUpdate;``

2020-10-16 10:03 UTC, Moskize91 commented on src/index.ts
> +    public on(cb: (status: PublicCombinedStatus, message?: string) => any): void {
这个有点反直觉。一般 ``obj.on(...)`` 都可以注册多个，而且和 ``obj.off(...)`` 对应。但实际上这个不是这个意思。

另外命名需要明确一下，比如 ``onStatusChange``

2020-10-16 10:03 UTC, Moskize91 commented on src/index.ts
> +let lastPublicCombinedStatus: PublicCombinedStatus = CombinePlayerStatus.PauseBuffering;
这个应该是成员变量把，为啥要全局唯一？不太明白。

命名有问题，可以叫做 ``previousCombineStatus``

2020-10-16 10:03 UTC, Moskize91 commented on src/index.ts
> +    private initVideoJS(): void {
除了添加监听，其他的操作应该挪到 factory 里进行。该对象构造时，得到的东西应该都已经准备好了

2020-10-16 10:03 UTC, Moskize91 commented on src/index.ts
> +    private handleWhiteboard(): void {
既然是初始化，就不该叫 handleWhiteboard，应该叫 initWhiteboard

2020-10-16 10:03 UTC, Moskize91 commented on src/index.ts
> +    private handleWhiteboardIsPlayable(): void {
应该叫 initWhiteboardIsPlayable，而且应该在 ``initWhiteboard()`` 里调用，而不是 constructor。

2020-10-16 10:03 UTC, Moskize91 commented on src/index.ts
> +let lastPublicCombinedStatus: PublicCombinedStatus = CombinePlayerStatus.PauseBuffering;
看了下后面的代码，应该叫 ``currentCombineStatus``

2020-10-16 10:15 UTC, BlackHole1 commented on src/index.ts
> +    private initVideoJS(): void {
这里的函数是为了 对 video 的状态做处理，以及添加监听器。是因为名字起的不规范，我改下名字

2020-10-16 10:17 UTC, BlackHole1 commented on src/index.ts
> +    private handleWhiteboard(): void {
问题同上，我修改下注释

2020-10-16 10:17 UTC, BlackHole1 commented on src/index.ts
> +    private initVideoJS(): void {
目前改成: `handleVideo`

2020-10-16 10:19 UTC, BlackHole1 commented on src/index.ts
> +    private handleWhiteboardIsPlayable(): void {
已改成在 `initWhiteboard` 里调用

2020-10-19 10:01 UTC, Moskize91 requested changes

2020-10-19 10:01 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    public onStatusChange(cb: (status: PublicCombinedStatus, message?: string) => any): void {
- 这是注册回调，而不是回调本身，因此必须以动词开头。建议叫 ``setOnStatusChange``。
- 该方法会覆盖上次的调用。如果用户想注册并监听多个 status 怎么办？
- 如果用户想注销监听怎么办？（这个修改可选，不做也行）

2020-10-19 10:01 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +                Promise.resolve().then((): void => {
这里为何要 ``Promise.resolve()``。建议加行注释解释一下这么做的原因。

2020-10-19 10:01 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    public async play(): Promise<void> {
改成：
```typescript
public play(): void {
        this.taskQueue.append(async () => {
            await this.setTriggerSource(TriggerSource.Plugin);

            const currentCombinedStatus = this.stateMachine.getCombinationStatus().current;

            if (currentCombinedStatus === CombinePlayerStatus.Pause) {
                await this.playByPause();
            } else if (currentCombinedStatus === CombinePlayerStatus.PauseBuffering) {
                await this.playByPauseBuffering();
            } else if (currentCombinedStatus === CombinePlayerStatus.Ended) {
                await this.playByEnded();
            }

            await this.setTriggerSource(TriggerSource.None);
        });
    }
```

2020-10-19 10:01 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    public async pause(): Promise<void> {
改成：
```typescript
    public pause(): void {
        this.taskQueue.append(async () => {
            await this.setTriggerSource(TriggerSource.Plugin);

            const currentCombinedStatus = this.stateMachine.getCombinationStatus().current;
            if (currentCombinedStatus === CombinePlayerStatus.Playing) {
                await this.pauseByPlaying();
            }

            await this.setTriggerSource(TriggerSource.None);
        });
    }
```

2020-10-19 10:01 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private setTriggerSource(source: TriggerSource): Promise<void> {
这个不必以 ``Promise<void>`` 返回。

2020-10-19 10:08 UTC, BlackHole1 commented on src/CombinePlayerImplement.ts
> +                Promise.resolve().then((): void => {
这个在上面已经有了一行注释：
// 使用 Promise 封装一层，转为异步，以保证用户传入的参数不会影响到插件本身。

2020-10-20 02:23 UTC, Moskize91 requested changes
将所有 playByPause 之类的命名改成 playWhenPause

2020-10-20 02:23 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private readonly onStatusUpdate: StatusChangeHandle = () => {};
如果这是一个私有 readonly 的回调闭包，且在 constructor 中初始化，那它其实完全等价于一个私有成员方法。
应该将它重构成一个私有方法。

2020-10-20 02:23 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +            this.onStatusUpdate(CombinePlayerStatus.PauseBuffering);
此处在 ``constructor`` 中调用，此时外界用户没有任何机会在 ``onStatusChangeHandleList`` 中添加内容来监听。
此处是否等价于直接 ``this.currentCombineStatus = CombinePlayerStatus.PauseBuffering;``

2020-10-20 02:23 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +        this.onStatusUpdate(CombinePlayerStatus.PauseBuffering);
此处参考 ``initVideo`` 的 request change

2020-10-20 02:23 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private playByPause(): Promise<void> {
改成 playWhenPause

2020-10-20 02:23 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private playByPauseBuffering(): Promise<void> {
改成 playWhenPauseBuffering

2020-10-20 02:23 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private playByEnded(): Promise<void> {
改成 playWhenEnded

2020-10-20 02:23 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private pauseByPlaying(): Promise<void> {
改成 pauseWhenPlaying

2020-10-21 02:38 UTC, Moskize91 requested changes

2020-10-21 02:38 UTC, Moskize91 commented on src/EventEmitter.ts
> +        this.listeners[eventName] = currentListener.filter(listener => {
如果 this.listeners 为 ``[]`` 时应该删掉整个数组

2020-10-21 02:38 UTC, Moskize91 commented on src/EventEmitter.ts
> +        this.listeners[eventName] = currentListener.filter(listener => {
用 indexOf + splice 来删除元素。这个方法会反复创建数组。

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +        const combineStatus = this.table[whiteboardStatusIndex][videoStatusIndex];
命名问题，这是 ``tableData`` 吧，怎么叫 combineStatus？

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +        cb: OneEventCallback,
删掉 ``OneEventCallback``，将该类型直接定义在这个文件。因为这个类型只有 stateMachine 用，为了高内聚性不应该写到外面。

建议写成：

```typescript
type onStatusUpdate = (current: AtomPlayerStatusPair, previous: AtomPlayerStatusPair) => Promise<void> | void;
```

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +            this.events.one(eventName, (previous, current, done) => {
应该改成：
```typescript
        return new Promise((resolve, reject) => {
            this.events.one(eventName, async (previous, current, done) => {
                try {
                    await cb(current, previous);
                    resolve();
                } catch (error) {
                    reject(error);
                } finally {
                    done();
                }
            });
        });
```

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +    public disabledHandler(crashHandler: AnyFunction): void {
应该改成 setOnCrashByDsiabledStatus。尽量别用 handler 这个单词，这个单词信息量几乎为零。

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +            this.allowStatusListWhenDisabled.forEach(({ video, whiteboard }) => {
这个逻辑出现了两次，建议封装成如下方法。

```typescript
    private shouldCrash(videoStatus: AtomPlayerStatus, whiteboardStatus: AtomPlayerStatus): boolean {
        let foundAnyStatusMatches = false;
        for (const {video, whiteboard} of this.allowStatusListWhenDisabled) {
            if (whiteboard === whiteboardStatus && video === videoStatus) {
                foundAnyStatusMatches = true;
                break;
            }
        }
        return !foundAnyStatusMatches;
    }
```

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +                const flag =
调用 ``this. shouldCrash()``

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +    public oneDisabled(allowStatusList: AtomPlayerStatusPair[]): Promise<AtomPlayerStatusCompose> {
改成 ``oneButNotCrashByDisabled``

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +    public oneDisabled(allowStatusList: AtomPlayerStatusPair[]): Promise<AtomPlayerStatusCompose> {
参数 ``allowStatusList`` 改为 ``statusIgnoreCrashByDisabled``，并在注释中说明。

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +     * 监听合法的 Disabled 状态
此处注释说明为什么要这个方法，为了解决什么问题，如何解决这个问题。而不是对方法名的简单描述。

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +            this.allowStatusListWhenDisabled = allowStatusList;
判断一下，如果重复调用，就报错。避免重复调用。

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +    private allowStatusListWhenDisabled: AtomPlayerStatusPair[] = [];
改为 ``statusIgnoreCrashByDisabled``

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +                }
在 else 分支中直接 ``reject(new Error("...."))``。因为走另一个分支意味着已经 crash 了，这里报个错以确保 promise 流程正常。

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +    public on(eventName: CombinePlayerStatus, cb: OnEventCallback): void {
``cb`` 换成 ``onStatusUpdate`` 类型，相印的，这个方法实现也改掉。和 ``one`` 一样的逻辑即可。

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +    private handleEvent(tableData: TableData): void {
改成 dispatchEvent

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +export type Table = readonly (readonly TableData[])[];
这不是 export

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +export type TableData = {
这不是 export

2020-10-21 02:38 UTC, Moskize91 commented on src/StateMachine.ts
> +export type GenerateTable = (whiteboard: AtomPlayerStatus, video: AtomPlayerStatus) => TableData;
这不是 export

2020-10-21 03:08 UTC, BlackHole1 commented on src/EventEmitter.ts
> +        this.listeners[eventName] = currentListener.filter(listener => {
反复创建数组，性能的开销基本可以忽略不计，我个人觉得使用 `filter` 比 `indexOf + splice` 的可读性好很多

2020-10-21 03:15 UTC, BlackHole1 commented on src/StateMachine.ts
> +            this.events.one(eventName, (previous, current, done) => {
已修改，不过其中的cb传参，我还是使用了对象的方式，因为我觉得这种方式在使用起来更加方便。可以直接使用js的解构。如:

```javascript
({ current }) => {
   // some code
}
```

2020-10-21 03:17 UTC, BlackHole1 commented on src/StateMachine.ts
> +    public disabledHandler(crashHandler: AnyFunction): void {
好的，其中 By 和 When 在使用场景上有什么需要注意的么。这里为啥不使用 `setOnCrashWhenDsiabledStatus`

2020-10-21 07:08 UTC, BlackHole1 commented on src/EventEmitter.ts
> +        this.listeners[eventName] = currentListener.filter(listener => {
使用 indexOf + splice 的写法:

```javascript
let index = currentListener.indexOf(cb);
if (index === -1) {
    // @ts-ignore
    index = currentListener.indexOf(cb.realCallbackFn);
}

if (index !== -1) {
    this.listeners[eventName].splice(index, 1);
}
```

2020-10-21 07:14 UTC, BlackHole1 commented on src/EventEmitter.ts
> +        this.listeners[eventName] = currentListener.filter(listener => {
并且这样有个问题，当使用方这么写的话，就会出现bug:

```
const fn = () => {};

event.addListener("eventName", addListener);
event.addListener("eventName", addListener);
```

如使用 IndexOf + splice，将只移除第一个。所以还要还需要一个循环:

```
const len = currentListener.length;
for (let i = 0; i < len; i++) {
    // @ts-ignore
    if (cb === currentListener[i] || cb === currentListener[i].realCallbackFn) {
        this.listeners[eventName].splice(index, 1);
    }
}
```

2020-10-22 02:42 UTC, Moskize91 requested changes
**除非迫不得已，不要用 ``resolve`` 来处理 Promise，而应该优先使用 async / await。**

如果一定要用 ``resolve``，必须处理 ``catch``，并认真检查每一处 ``resolve / catch`` 是否最终被调用。显然你也没有做到这个程度。要做到这个程度很难，需要非常仔细严谨地写代码。所以还不如用 async / await，编译器已经帮你搞定了。

2020-10-22 02:42 UTC, Moskize91 commented on src/EventEmitter.ts
> +        this.listeners[eventName] = currentListener.filter(listener => {
这样就行了：

```typescript
for (let i = 0; i < listeners.length; i ++) {
    const listener = listeners[i];
    if (listener === ***) {
        listeners.splice(i, 1);
        i --;
    }
}
```

2020-10-22 02:42 UTC, Moskize91 commented on src/EventEmitter.ts
> +        const currentListener = this.getEvent(eventName);
不要叫 ``currentListener``，叫 ``currentListeners``。这是个数组，用复数形式。

2020-10-22 02:42 UTC, Moskize91 commented on src/EventEmitter.ts
> +        if (isNotFn(cb)) {
应该直接报错，而不是忽略！！

2020-10-22 02:42 UTC, Moskize91 commented on src/EventEmitter.ts
> +const isNotFn = (fn: AnyFunction): boolean => {
``typeof fn !== "function"`` 行不行？

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private playWhenPause(): Promise<void> {
这里可以消灭 ``resolve()`` 方法。
将整个方法改成 ``async playWhenPause``，然后删掉 ``return new Promise``，将这段代码移动到方法体末尾。
```typescript
await this.stateMachine
    .one(CombinePlayerStatus.Playing, async () => {
        this.onStatusUpdate(CombinePlayerStatus.Playing);
    })
```

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private playWhenPauseBuffering(): Promise<void> {
- 这个方法体太大，至少可以拆成 3 个子方法。而这 3 个子方法还能拆成更多子子方法，请先重构。
- 这个方法可以干掉 ``resolve()``，参考我上一条留言重构。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private playWhenEnded(): Promise<void> {
干掉 ``resolve()``，参考我之前的留言。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private pauseWhenPlaying(): Promise<void> {
干掉 ``resolve()``，参考我之前的留言。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private seekWhenPlaying(ms: number): Promise<void> {
干掉 ``resolve()``，参考我之前的留言。
这里可以用到 ``Promise.race`` 或 ``Promise.all`` 之类的方法，重构之前可以想一想怎么等效重构。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private seekWhenPause(ms: number): Promise<void> {
- 干掉 ``resolve()``，参考我之前的留言。
- 这个方法可以拆成更多的子方法

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private pauseWhiteboardWhenVideoWaiting(): Promise<void> {
干掉 ``resolve()``，参考我之前的留言。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private playingWhiteboardWhenVideoPlaying(isDropFrame: boolean): Promise<void> {
干掉 ``resolve()``，参考我之前的留言。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private pauseVideoWhenWhiteboardBuffering(): Promise<void> {
干掉 ``resolve()``，参考我之前的留言。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private playingVideoWhenWhiteboardPlaying(): Promise<void> {
干掉 ``resolve()``，参考我之前的留言。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private pauseVideoWhenWhiteboardEnded(): Promise<void> {
干掉 ``resolve()``，参考我之前的留言。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private pauseWhiteboardWhenVideoEnded(): Promise<void> {
干掉 ``resolve()``，参考我之前的留言。

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private initDisabledStatusHandler(): void {
改名为 ``initOnCrashByDisabledStatusCallback``

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +    private initDisabledStatusHandler(): void {
此时应该在注释里解释一下为什么要监听这个

2020-10-22 02:42 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +                    cb(status, message);
cb 应该加上 try catch 语句，这个 cb 是用户传进来的，可能报错

2020-10-22 03:05 UTC, BlackHole1 commented on src/CombinePlayerImplement.ts
> +                    cb(status, message);
如果 cb 是同步的，则即使报错，也会出现 Error，没有必要再包一层

这里，我只处理了  cb 是异步函数，并且出现错误的情况

2020-10-22 03:26 UTC, BlackHole1 commented on src/CombinePlayerImplement.ts
> +    private seekWhenPause(ms: number): Promise<void> {
我所能看到能拆的，只有一个获取 白板和video 持续时长的

2020-10-26 02:28 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +                return new Promise(resolve => {
这里为啥不用 async？resolve 有时不会调用，会无限 padding 吧？

2020-10-26 02:28 UTC, Moskize91 commented on src/CombinePlayerImplement.ts
> +            ({ current }): Promise<void> => {
这里看起来在故意不调用 resolve？

2020-10-26 02:31 UTC, Moskize91 requested changes
有些 resolve 似乎不是永远会被调用

2020-10-26 02:32 UTC, BlackHole1 commented on src/CombinePlayerImplement.ts
> +            ({ current }): Promise<void> => {
是的，Ended这个情况会多次触发，但是真正结束的只有一个，所以这里进行判断，只有真正符合逻辑的，才是真正的完成。
因为对 `combinePlayerStatusWhenEnded` 进行了 await ，一旦这个返回了 resolve，那么就会错误的认为当前上下文结束了。不符合程序逻辑

2020-10-26 05:38 UTC, Moskize91 commented on package.json
> +  "version": "0.0.1-alpha.1",
版本改成 0.0.1

2020-10-26 05:40 UTC, Moskize91 commented on .npmignore
> +.eslintignore
不要用黑名单机制，直接用白名单机制。
可以参考这篇文章：https://www.zcfy.cc/article/for-the-love-of-god-don-t-use-npmignore

2020-10-26 05:41 UTC, Moskize91 requested changes
最后，修改一下 README.md 文件。简单说明启动的前置条件，如何开发，如果启 example。

2020-10-26 08:35 UTC, Moskize91 approved these changes

2020-10-26 08:35 UTC, merged